### PR TITLE
Lesson-1-6

### PR DESCRIPTION
**Pull request by aokounev**
Lesson 1.6

### CODE REVIEW

**Comment by avspeed** [comment]
@aokounev great job ! You should try to validate the todo item that you add and if it is blank do not add it.

**Comment by aokounev** [comment]
I will add:

let addTodo = (newTodo) => {
    if (newTodo.title !== "") 
    setTodoList([...todoList, newTodo]);
  };

**Comment by aokounev** [comment]
@avspeed I changed the code per your suggestion.  Would that work?

**Comment by JamieBort** [comment]
Everything looks good!

**Pull request merged**
